
// Mono.Globalization.Unicode.Normalization
REG_ICALL("Mono.Globalization.Unicode.Normalization::load_normalization_resource(System.IntPtr&,System.IntPtr&,System.IntPtr&,System.IntPtr&,System.IntPtr&,System.IntPtr&)", mscorlib::Mono::Globalization::Unicode::Normalization::load_normalization_resource)

// Mono.Interop.ComInteropProxy
REG_ICALL("Mono.Interop.ComInteropProxy::AddProxy(System.IntPtr,Mono.Interop.ComInteropProxy)", mscorlib::Mono::Interop::ComInteropProxy::AddProxy)
REG_ICALL("Mono.Interop.ComInteropProxy::FindProxy(System.IntPtr)", mscorlib::Mono::Interop::ComInteropProxy::FindProxy)

// Mono.Runtime
REG_ICALL("Mono.Runtime::GetDisplayName()", mscorlib::Mono::Runtime::GetDisplayName)
REG_ICALL("Mono.Runtime::mono_runtime_install_handlers()", mscorlib::Mono::Runtime::mono_runtime_install_handlers)

// Mono.Security.Cryptography.KeyPairPersistence
REG_ICALL("Mono.Security.Cryptography.KeyPairPersistence::_CanSecure(System.String)", mscorlib::Mono::Security::Cryptography::KeyPairPersistence::_CanSecure)
REG_ICALL("Mono.Security.Cryptography.KeyPairPersistence::_IsMachineProtected(System.String)", mscorlib::Mono::Security::Cryptography::KeyPairPersistence::_IsMachineProtected)
REG_ICALL("Mono.Security.Cryptography.KeyPairPersistence::_IsUserProtected(System.String)", mscorlib::Mono::Security::Cryptography::KeyPairPersistence::_IsUserProtected)
REG_ICALL("Mono.Security.Cryptography.KeyPairPersistence::_ProtectMachine(System.String)", mscorlib::Mono::Security::Cryptography::KeyPairPersistence::_ProtectMachine)
REG_ICALL("Mono.Security.Cryptography.KeyPairPersistence::_ProtectUser(System.String)", mscorlib::Mono::Security::Cryptography::KeyPairPersistence::_ProtectUser)

// System.__ComObject
REG_ICALL("System.__ComObject::CreateRCW(System.Type)", mscorlib::System::__ComObject::CreateRCW)
REG_ICALL("System.__ComObject::GetInterfaceInternal(System.Type,System.Boolean)", mscorlib::System::__ComObject::GetInterfaceInternal)
REG_ICALL("System.__ComObject::ReleaseInterfaces()", mscorlib::System::__ComObject::ReleaseInterfaces)

// System.Activator
REG_ICALL("System.Activator::CreateInstanceInternal(System.Type)", mscorlib::System::Activator::CreateInstanceInternal)

// System.AppDomain
REG_ICALL("System.AppDomain::createDomain(System.String,System.AppDomainSetup)", mscorlib::System::AppDomain::createDomain)
REG_ICALL("System.AppDomain::ExecuteAssembly(System.Reflection.Assembly,System.String[])", mscorlib::System::AppDomain::ExecuteAssembly)
REG_ICALL("System.AppDomain::GetAssemblies(System.Boolean)",mscorlib::System::AppDomain::GetAssemblies)
REG_ICALL("System.AppDomain::getCurDomain()", mscorlib::System::AppDomain::getCurDomain)
REG_ICALL("System.AppDomain::GetData(System.String)", mscorlib::System::AppDomain::GetData)
REG_ICALL("System.AppDomain::getFriendlyName()", mscorlib::System::AppDomain::getFriendlyName)
REG_ICALL("System.AppDomain::getRootDomain()", mscorlib::System::AppDomain::getRootDomain)
REG_ICALL("System.AppDomain::getSetup()", mscorlib::System::AppDomain::getSetup)
REG_ICALL("System.AppDomain::InternalGetContext()", mscorlib::System::AppDomain::InternalGetContext)
REG_ICALL("System.AppDomain::InternalGetDefaultContext()", mscorlib::System::AppDomain::InternalGetDefaultContext)
REG_ICALL("System.AppDomain::InternalGetProcessGuid(System.String)", mscorlib::System::AppDomain::InternalGetProcessGuid)
REG_ICALL("System.AppDomain::InternalIsFinalizingForUnload(System.Int32)", mscorlib::System::AppDomain::InternalIsFinalizingForUnload)
REG_ICALL("System.AppDomain::InternalPopDomainRef()", mscorlib::System::AppDomain::InternalPopDomainRef)
REG_ICALL("System.AppDomain::InternalPushDomainRef(System.AppDomain)", mscorlib::System::AppDomain::InternalPushDomainRef)
REG_ICALL("System.AppDomain::InternalPushDomainRefByID(System.Int32)", mscorlib::System::AppDomain::InternalPushDomainRefByID)
REG_ICALL("System.AppDomain::InternalSetContext(System.Runtime.Remoting.Contexts.Context)", mscorlib::System::AppDomain::InternalSetContext)
REG_ICALL("System.AppDomain::InternalSetDomain(System.AppDomain)", mscorlib::System::AppDomain::InternalSetDomain)
REG_ICALL("System.AppDomain::InternalSetDomainByID(System.Int32)", mscorlib::System::AppDomain::InternalSetDomainByID)
REG_ICALL("System.AppDomain::InternalUnload(System.Int32)", mscorlib::System::AppDomain::InternalUnload)
REG_ICALL("System.AppDomain::LoadAssembly(System.String,System.Security.Policy.Evidence,System.Boolean)", mscorlib::System::AppDomain::LoadAssembly)
REG_ICALL("System.AppDomain::LoadAssemblyRaw(System.Byte[],System.Byte[],System.Security.Policy.Evidence,System.Boolean)", mscorlib::System::AppDomain::LoadAssemblyRaw)
REG_ICALL("System.AppDomain::SetData(System.String,System.Object)", mscorlib::System::AppDomain::SetData)

// System.ArgIterator
REG_ICALL("System.ArgIterator::IntGetNextArg()", mscorlib::System::ArgIterator::IntGetNextArg_mscorlib_System_TypedReference)
REG_ICALL("System.ArgIterator::IntGetNextArg(System.IntPtr)", mscorlib::System::ArgIterator::IntGetNextArg_mscorlib_System_TypedReference_mscorlib_System_IntPtr)
REG_ICALL("System.ArgIterator::IntGetNextArgType()", mscorlib::System::ArgIterator::IntGetNextArgType)
REG_ICALL("System.ArgIterator::Setup(System.IntPtr,System.IntPtr)", mscorlib::System::ArgIterator::Setup)

// System.Array
REG_ICALL("System.Array::ClearInternal(System.Array,System.Int32,System.Int32)", mscorlib::System::Array::ClearInternal)
REG_ICALL("System.Array::Clone()", mscorlib::System::Array::Clone)
REG_ICALL("System.Array::CreateInstanceImpl(System.Type,System.Int32[],System.Int32[])", mscorlib::System::Array::CreateInstanceImpl)
REG_ICALL("System.Array::FastCopy(System.Array,System.Int32,System.Array,System.Int32,System.Int32)", mscorlib::System::Array::FastCopy)
REG_ICALL("System.Array::GetLength(System.Int32)", mscorlib::System::Array::GetLength)
REG_ICALL("System.Array::GetLowerBound(System.Int32)", mscorlib::System::Array::GetLowerBound)
REG_ICALL("System.Array::GetRank()", mscorlib::System::Array::GetRank)
REG_ICALL("System.Array::GetValue(System.Int32[])", mscorlib::System::Array::GetValue)
REG_ICALL("System.Array::GetValueImpl(System.Int32)", mscorlib::System::Array::GetValueImpl)
REG_ICALL("System.Array::SetValue(System.Object,System.Int32[])", mscorlib::System::Array::SetValue)
REG_ICALL("System.Array::SetValueImpl(System.Object,System.Int32)", mscorlib::System::Array::SetValueImpl)

// System.Buffer
REG_ICALL("System.Buffer::BlockCopyInternal(System.Array,System.Int32,System.Array,System.Int32,System.Int32)", mscorlib::System::Buffer::BlockCopyInternal)
REG_ICALL("System.Buffer::ByteLengthInternal(System.Array)", mscorlib::System::Buffer::ByteLengthInternal)
REG_ICALL("System.Buffer::GetByteInternal(System.Array,System.Int32)", mscorlib::System::Buffer::GetByteInternal)
REG_ICALL("System.Buffer::SetByteInternal(System.Array,System.Int32,System.Int32)", mscorlib::System::Buffer::SetByteInternal)

// System.Char
REG_ICALL("System.Char::GetDataTablePointers(System.Byte*&,System.Byte*&,System.Double*&,System.UInt16*&,System.UInt16*&,System.UInt16*&,System.UInt16*&)", mscorlib::System::Char::GetDataTablePointers)

// System.Configuration.DefaultConfig
REG_ICALL("System.Configuration.DefaultConfig::get_bundled_machine_config()", System::System::Configuration::DefaultConfig::get_bundled_machine_config)
REG_ICALL("System.Configuration.DefaultConfig::get_machine_config_path()", System::System::Configuration::DefaultConfig::get_machine_config_path)

// System.Configuration.InternalConfigurationHost
REG_ICALL("System.Configuration.InternalConfigurationHost::get_bundled_machine_config()", System::System::Configuration::InternalConfigurationHost::get_bundled_machine_config)

// System.ConsoleDriver
REG_ICALL("System.ConsoleDriver::InternalKeyAvailable(System.Int32)", mscorlib::System::ConsoleDriver::InternalKeyAvailable)
REG_ICALL("System.ConsoleDriver::Isatty(System.IntPtr)", mscorlib::System::ConsoleDriver::Isatty)
REG_ICALL("System.ConsoleDriver::SetBreak(System.Boolean)", mscorlib::System::ConsoleDriver::SetBreak)
REG_ICALL("System.ConsoleDriver::SetEcho(System.Boolean)", mscorlib::System::ConsoleDriver::SetEcho)
REG_ICALL("System.ConsoleDriver::TtySetup(System.String,System.String,System.Byte[]&,System.Int32*&)", mscorlib::System::ConsoleDriver::TtySetup)

// System.Convert
REG_ICALL("System.Convert::InternalFromBase64CharArray(System.Char[],System.Int32,System.Int32)", mscorlib::System::Convert::InternalFromBase64CharArray)
REG_ICALL("System.Convert::InternalFromBase64String(System.String,System.Boolean)", mscorlib::System::Convert::InternalFromBase64String)

// System.CurrentSystemTimeZone
REG_ICALL("System.CurrentSystemTimeZone::GetTimeZoneData(System.Int32,System.Int64[]&,System.String[]&)", mscorlib::System::CurrentSystemTimeZone::GetTimeZoneData)

// System.ComponentModel.Win32Exception
REG_ICALL("System.ComponentModel.Win32Exception::W32ErrorMessage(System.Int32)", System::System::ComponentModel::Win32Exception::W32ErrorMessage)

// System.DateTime
REG_ICALL("System.DateTime::GetNow()", mscorlib::System::DateTime::GetNow)
REG_ICALL("System.DateTime::GetTimeMonotonic()", mscorlib::System::DateTime::GetTimeMonotonic)

// System.Decimal
REG_ICALL("System.Decimal::decimal2double(System.Decimal&)", mscorlib::System::Decimal::decimal2double)
REG_ICALL("System.Decimal::decimal2Int64(System.Decimal&,System.Int64&)", mscorlib::System::Decimal::decimal2Int64)
REG_ICALL("System.Decimal::decimal2string(System.Decimal&,System.Int32,System.Int32,System.Char[],System.Int32,System.Int32&,System.Int32&)", mscorlib::System::Decimal::decimal2string)
REG_ICALL("System.Decimal::decimal2UInt64(System.Decimal&,System.UInt64&)", mscorlib::System::Decimal::decimal2UInt64)
REG_ICALL("System.Decimal::decimalCompare(System.Decimal&,System.Decimal&)", mscorlib::System::Decimal::decimalCompare)
REG_ICALL("System.Decimal::decimalDiv(System.Decimal&,System.Decimal&,System.Decimal&)", mscorlib::System::Decimal::decimalDiv)
REG_ICALL("System.Decimal::decimalFloorAndTrunc(System.Decimal&,System.Int32)", mscorlib::System::Decimal::decimalFloorAndTrunc)
REG_ICALL("System.Decimal::decimalIncr(System.Decimal&,System.Decimal&)", mscorlib::System::Decimal::decimalIncr)
REG_ICALL("System.Decimal::decimalIntDiv(System.Decimal&,System.Decimal&,System.Decimal&)", mscorlib::System::Decimal::decimalIntDiv)
REG_ICALL("System.Decimal::decimalMult(System.Decimal&,System.Decimal&)", mscorlib::System::Decimal::decimalMult)
REG_ICALL("System.Decimal::decimalSetExponent(System.Decimal&,System.Int32)", mscorlib::System::Decimal::decimalSetExponent)
REG_ICALL("System.Decimal::string2decimal(System.Decimal&,System.String,System.UInt32,System.Int32)", mscorlib::System::Decimal::string2decimal)

// System.Delegate
REG_ICALL("System.Delegate::CreateDelegate_internal(System.Type,System.Object,System.Reflection.MethodInfo,System.Boolean)", mscorlib::System::Delegate::CreateDelegate_internal)
REG_ICALL("System.Delegate::SetMulticastInvoke()", mscorlib::System::Delegate::SetMulticastInvoke)

// System.Diagnostics.Debugger
REG_ICALL("System.Diagnostics.Debugger::IsAttached_internal()", mscorlib::System::Diagnostics::Debugger::IsAttached_internal)

// System.Diagnostics.DefaultTraceListener
REG_ICALL("System.Diagnostics.DefaultTraceListener::WriteWindowsDebugString(System.String)", System::System::Diagnostics::DefaultTraceListener::WriteWindowsDebugString)

// System.Diagnostics.FileVersionInfo
REG_ICALL("System.Diagnostics.FileVersionInfo::GetVersionInfo_internal(System.String)", System::System::Diagnostics::FileVersionInfo::GetVersionInfo_internal)

// System.Diagnostics.PerformanceCounter
REG_ICALL("System.Diagnostics.PerformanceCounter::FreeData(System.IntPtr)", System::System::Diagnostics::PerformanceCounter::FreeData)
REG_ICALL("System.Diagnostics.PerformanceCounter::GetImpl(System.String,System.String,System.String,System.String,System.Diagnostics.PerformanceCounterType&,System.Boolean&)", System::System::Diagnostics::PerformanceCounter::GetImpl)
REG_ICALL("System.Diagnostics.PerformanceCounter::GetSample(System.IntPtr,System.Boolean,System.Diagnostics.CounterSample&)", System::System::Diagnostics::PerformanceCounter::GetSample)
REG_ICALL("System.Diagnostics.PerformanceCounter::UpdateValue(System.IntPtr,System.Boolean,System.Int64)", System::System::Diagnostics::PerformanceCounter::UpdateValue)

// System.Diagnostics.PerformanceCounterCategory
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::CategoryDelete(System.String)", System::System::Diagnostics::PerformanceCounterCategory::CategoryDelete)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::CategoryHelpInternal(System.String,System.String)", System::System::Diagnostics::PerformanceCounterCategory::CategoryHelpInternal)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::CounterCategoryExists(System.String,System.String,System.String)", System::System::Diagnostics::PerformanceCounterCategory::CounterCategoryExists)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::Create(System.String,System.String,System.Diagnostics.PerformanceCounterCategoryType,System.Diagnostics.CounterCreationData[])", System::System::Diagnostics::PerformanceCounterCategory::Create)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::GetCategoryNames(System.String)", System::System::Diagnostics::PerformanceCounterCategory::GetCategoryNames)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::GetCounterNames(System.String,System.String)", System::System::Diagnostics::PerformanceCounterCategory::GetCounterNames)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::GetInstanceNames(System.String,System.String)", System::System::Diagnostics::PerformanceCounterCategory::GetInstanceNames)
REG_ICALL("System.Diagnostics.PerformanceCounterCategory::InstanceExistsInternal(System.String,System.String,System.String)", System::System::Diagnostics::PerformanceCounterCategory::InstanceExistsInternal)

// System.Diagnostics.Process
REG_ICALL("System.Diagnostics.Process::CreateProcess_internal(System.Diagnostics.ProcessStartInfo,System.IntPtr,System.IntPtr,System.IntPtr,System.Diagnostics.Process/ProcInfo&)", System::System::Diagnostics::Process::CreateProcess_internal)
REG_ICALL("System.Diagnostics.Process::ExitCode_internal(System.IntPtr)", System::System::Diagnostics::Process::ExitCode_internal)
REG_ICALL("System.Diagnostics.Process::ExitTime_internal(System.IntPtr)", System::System::Diagnostics::Process::ExitTime_internal)
REG_ICALL("System.Diagnostics.Process::GetModules_internal(System.IntPtr)", System::System::Diagnostics::Process::GetModules_internal)
REG_ICALL("System.Diagnostics.Process::GetPid_internal()", System::System::Diagnostics::Process::GetPid_internal)
REG_ICALL("System.Diagnostics.Process::GetPriorityClass(System.IntPtr,System.Int32&)", System::System::Diagnostics::Process::GetPriorityClass)
REG_ICALL("System.Diagnostics.Process::GetProcess_internal(System.Int32)", System::System::Diagnostics::Process::GetProcess_internal)
REG_ICALL("System.Diagnostics.Process::GetProcessData(System.Int32,System.Int32,System.Int32&)", System::System::Diagnostics::Process::GetProcessData)
REG_ICALL("System.Diagnostics.Process::GetProcesses_internal()", System::System::Diagnostics::Process::GetProcesses_internal)
REG_ICALL("System.Diagnostics.Process::GetWorkingSet_internal(System.IntPtr,System.Int32&,System.Int32&)", System::System::Diagnostics::Process::GetWorkingSet_internal)
REG_ICALL("System.Diagnostics.Process::Kill_internal(System.IntPtr,System.Int32)", System::System::Diagnostics::Process::Kill_internal)
REG_ICALL("System.Diagnostics.Process::Process_free_internal(System.IntPtr)", System::System::Diagnostics::Process::Process_free_internal)
REG_ICALL("System.Diagnostics.Process::ProcessName_internal(System.IntPtr)", System::System::Diagnostics::Process::ProcessName_internal)
REG_ICALL("System.Diagnostics.Process::SetPriorityClass(System.IntPtr,System.Int32,System.Int32&)", System::System::Diagnostics::Process::SetPriorityClass)
REG_ICALL("System.Diagnostics.Process::SetWorkingSet_internal(System.IntPtr,System.Int32,System.Int32,System.Boolean)", System::System::Diagnostics::Process::SetWorkingSet_internal)
REG_ICALL("System.Diagnostics.Process::ShellExecuteEx_internal(System.Diagnostics.ProcessStartInfo,System.Diagnostics.Process/ProcInfo&)", System::System::Diagnostics::Process::ShellExecuteEx_internal)
REG_ICALL("System.Diagnostics.Process::StartTime_internal(System.IntPtr)", System::System::Diagnostics::Process::StartTime_internal)
REG_ICALL("System.Diagnostics.Process::Times(System.IntPtr,System.Int32)", System::System::Diagnostics::Process::Times)
REG_ICALL("System.Diagnostics.Process::WaitForExit_internal(System.IntPtr,System.Int32)", System::System::Diagnostics::Process::WaitForExit_internal)
REG_ICALL("System.Diagnostics.Process::WaitForInputIdle_internal(System.IntPtr,System.Int32)", System::System::Diagnostics::Process::WaitForInputIdle_internal)

// System.Diagnostics.StackFrame
REG_ICALL("System.Diagnostics.StackFrame::get_frame_info(System.Int32,System.Boolean,System.Reflection.MethodBase&,System.Int32&,System.Int32&,System.String&,System.Int32&,System.Int32&)", mscorlib::System::Diagnostics::StackFrame::get_frame_info)

// System.Diagnostics.StackTrace
REG_ICALL("System.Diagnostics.StackTrace::get_trace(System.Exception,System.Int32,System.Boolean)", mscorlib::System::Diagnostics::StackTrace::get_trace)

// System.Diagnostics.Stopwatch
REG_ICALL("System.Diagnostics.Stopwatch::GetTimestamp()", System::System::Diagnostics::Stopwatch::GetTimestamp)

// System.Double
REG_ICALL("System.Double::ParseImpl(System.Byte*,System.Double&)", mscorlib::System::Double::ParseImpl)

// System.Enum
REG_ICALL("System.Enum::compare_value_to(System.Object)", mscorlib::System::Enum::compare_value_to)
REG_ICALL("System.Enum::get_hashcode()", mscorlib::System::Enum::get_hashcode)
REG_ICALL("System.Enum::get_underlying_type(System.Type)", mscorlib::System::Enum::get_underlying_type)
REG_ICALL("System.Enum::get_value()", mscorlib::System::Enum::get_value)
REG_ICALL("System.Enum::ToObject(System.Type,System.Object)", mscorlib::System::Enum::ToObject)

// System.Environment
REG_ICALL("System.Environment::Exit(System.Int32)", mscorlib::System::Environment::Exit)
REG_ICALL("System.Environment::get_EmbeddingHostName()", mscorlib::System::Environment::get_EmbeddingHostName)
REG_ICALL("System.Environment::get_ExitCode()", mscorlib::System::Environment::get_ExitCode)
REG_ICALL("System.Environment::get_HasShutdownStarted()", mscorlib::System::Environment::get_HasShutdownStarted)
REG_ICALL("System.Environment::get_MachineName()", mscorlib::System::Environment::get_MachineName)
REG_ICALL("System.Environment::get_NewLine()", mscorlib::System::Environment::get_NewLine)
REG_ICALL("System.Environment::get_Platform()", mscorlib::System::Environment::get_Platform)
REG_ICALL("System.Environment::get_ProcessorCount()", mscorlib::System::Environment::get_ProcessorCount)
REG_ICALL("System.Environment::get_SocketSecurityEnabled()", mscorlib::System::Environment::get_SocketSecurityEnabled)
REG_ICALL("System.Environment::get_TickCount()", mscorlib::System::Environment::get_TickCount)
REG_ICALL("System.Environment::get_UserName()", mscorlib::System::Environment::get_UserName)
REG_ICALL("System.Environment::GetCommandLineArgs()", mscorlib::System::Environment::GetCommandLineArgs)
REG_ICALL("System.Environment::GetEnvironmentVariableNames()", mscorlib::System::Environment::GetEnvironmentVariableNames)
REG_ICALL("System.Environment::GetLogicalDrivesInternal()", mscorlib::System::Environment::GetLogicalDrivesInternal)
REG_ICALL("System.Environment::GetMachineConfigPath()", mscorlib::System::Environment::GetMachineConfigPath)
REG_ICALL("System.Environment::GetOSVersionString()", mscorlib::System::Environment::GetOSVersionString)
REG_ICALL("System.Environment::GetWindowsFolderPath(System.Int32)", mscorlib::System::Environment::GetWindowsFolderPath)
REG_ICALL("System.Environment::internalBroadcastSettingChange()", mscorlib::System::Environment::internalBroadcastSettingChange)
REG_ICALL("System.Environment::internalGetEnvironmentVariable(System.String)", mscorlib::System::Environment::internalGetEnvironmentVariable)
REG_ICALL("System.Environment::internalGetGacPath()", mscorlib::System::Environment::internalGetGacPath)
REG_ICALL("System.Environment::internalGetHome()", mscorlib::System::Environment::internalGetHome)
REG_ICALL("System.Environment::InternalSetEnvironmentVariable(System.String,System.String)", mscorlib::System::Environment::InternalSetEnvironmentVariable)
REG_ICALL("System.Environment::set_ExitCode(System.Int32)", mscorlib::System::Environment::set_ExitCode)

// System.GC
REG_ICALL("System.GC::CollectionCount(System.Int32)", mscorlib::System::GC::CollectionCount)
REG_ICALL("System.GC::get_MaxGeneration()", mscorlib::System::GC::get_MaxGeneration)
REG_ICALL("System.GC::GetGeneration(System.Object)", mscorlib::System::GC::GetGeneration)
REG_ICALL("System.GC::GetTotalMemory(System.Boolean)", mscorlib::System::GC::GetTotalMemory)
REG_ICALL("System.GC::InternalCollect(System.Int32)", mscorlib::System::GC::InternalCollect)
REG_ICALL("System.GC::KeepAlive(System.Object)", mscorlib::System::GC::KeepAlive)
REG_ICALL("System.GC::RecordPressure(System.Int64)", mscorlib::System::GC::RecordPressure)
REG_ICALL("System.GC::ReRegisterForFinalize(System.Object)", mscorlib::System::GC::ReRegisterForFinalize)
REG_ICALL("System.GC::SuppressFinalize(System.Object)", mscorlib::System::GC::SuppressFinalize)
REG_ICALL("System.GC::WaitForPendingFinalizers()", mscorlib::System::GC::WaitForPendingFinalizers)

// System.Globalization.CompareInfo
REG_ICALL("System.Globalization.CompareInfo::assign_sortkey(System.Object,System.String,System.Globalization.CompareOptions)", mscorlib::System::Globalization::CompareInfo::assign_sortkey)
REG_ICALL("System.Globalization.CompareInfo::construct_compareinfo(System.String)", mscorlib::System::Globalization::CompareInfo::construct_compareinfo)
REG_ICALL("System.Globalization.CompareInfo::free_internal_collator()", mscorlib::System::Globalization::CompareInfo::free_internal_collator)
REG_ICALL("System.Globalization.CompareInfo::internal_compare(System.String,System.Int32,System.Int32,System.String,System.Int32,System.Int32,System.Globalization.CompareOptions)", mscorlib::System::Globalization::CompareInfo::internal_compare)
REG_ICALL("System.Globalization.CompareInfo::internal_index(System.String,System.Int32,System.Int32,System.Char,System.Globalization.CompareOptions,System.Boolean)", mscorlib::System::Globalization::CompareInfo::internal_index)
REG_ICALL("System.Globalization.CompareInfo::internal_index(System.String,System.Int32,System.Int32,System.String,System.Globalization.CompareOptions,System.Boolean)", mscorlib::System::Globalization::CompareInfo::internal_index)

// System.Globalization.CultureInfo
REG_ICALL("System.Globalization.CultureInfo::construct_datetime_format()", mscorlib::System::Globalization::CultureInfo::construct_datetime_format)
REG_ICALL("System.Globalization.CultureInfo::construct_internal_locale_from_current_locale(System.Globalization.CultureInfo)", mscorlib::System::Globalization::CultureInfo::construct_internal_locale_from_current_locale)
REG_ICALL("System.Globalization.CultureInfo::construct_internal_locale_from_lcid(System.Int32)", mscorlib::System::Globalization::CultureInfo::construct_internal_locale_from_lcid)
REG_ICALL("System.Globalization.CultureInfo::construct_internal_locale_from_name(System.String)", mscorlib::System::Globalization::CultureInfo::construct_internal_locale_from_name)
REG_ICALL("System.Globalization.CultureInfo::construct_internal_locale_from_specific_name(System.Globalization.CultureInfo,System.String)", mscorlib::System::Globalization::CultureInfo::construct_internal_locale_from_specific_name)
REG_ICALL("System.Globalization.CultureInfo::construct_number_format()", mscorlib::System::Globalization::CultureInfo::construct_number_format)
REG_ICALL("System.Globalization.CultureInfo::internal_get_cultures(System.Boolean,System.Boolean,System.Boolean)", mscorlib::System::Globalization::CultureInfo::internal_get_cultures)
REG_ICALL("System.Globalization.CultureInfo::internal_is_lcid_neutral(System.Int32,System.Boolean&)", mscorlib::System::Globalization::CultureInfo::internal_is_lcid_neutral)

// System.Globalization.RegionInfo
REG_ICALL("System.Globalization.RegionInfo::construct_internal_region_from_name(System.String)", mscorlib::System::Globalization::RegionInfo::construct_internal_region_from_name)

// System.IO.DriveInfo
REG_ICALL("System.IO.DriveInfo::GetDiskFreeSpaceInternal(System.String,System.UInt64&,System.UInt64&,System.UInt64&,System.IO.MonoIOError&)", mscorlib::System::IO::DriveInfo::GetDiskFreeSpaceInternal)
REG_ICALL("System.IO.DriveInfo::GetDriveTypeInternal(System.String)", mscorlib::System::IO::DriveInfo::GetDriveTypeInternal)

// System.IO.FAMWatcher
REG_ICALL("System.IO.FAMWatcher::InternalFAMNextEvent(System.IO.FAMConnection&,System.String&,System.Int32&,System.Int32&)", System::System::IO::FAMWatcher::InternalFAMNextEvent)

// System.IO.FileSystemWatcher
REG_ICALL("System.IO.FileSystemWatcher::InternalSupportsFSW()", System::System::IO::FileSystemWatcher::InternalSupportsFSW)

// System.IO.InotifyWatcher
REG_ICALL("System.IO.InotifyWatcher::AddWatch(System.IntPtr,System.String,System.IO.InotifyMask)", System::System::IO::InotifyWatcher::AddWatch)
REG_ICALL("System.IO.InotifyWatcher::GetInotifyInstance()", System::System::IO::InotifyWatcher::GetInotifyInstance)
REG_ICALL("System.IO.InotifyWatcher::RemoveWatch(System.IntPtr,System.Int32)", System::System::IO::InotifyWatcher::RemoveWatch)

// System.IO.MonoIO
REG_ICALL("System.IO.MonoIO::Close(System.IntPtr,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Close)
REG_ICALL("System.IO.MonoIO::CopyFile(System.String,System.String,System.Boolean,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::CopyFile)
REG_ICALL("System.IO.MonoIO::CreateDirectory(System.String,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::CreateDirectory)
REG_ICALL("System.IO.MonoIO::CreatePipe(System.IntPtr&,System.IntPtr&)", mscorlib::System::IO::MonoIO::CreatePipe)
REG_ICALL("System.IO.MonoIO::DeleteFile(System.String,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::DeleteFile)
REG_ICALL("System.IO.MonoIO::DuplicateHandle(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr&,System.Int32,System.Int32,System.Int32)", mscorlib::System::IO::MonoIO::DuplicateHandle)
REG_ICALL("System.IO.MonoIO::Flush(System.IntPtr,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Flush)
REG_ICALL("System.IO.MonoIO::get_AltDirectorySeparatorChar()", mscorlib::System::IO::MonoIO::get_AltDirectorySeparatorChar)
REG_ICALL("System.IO.MonoIO::get_ConsoleError()", mscorlib::System::IO::MonoIO::get_ConsoleError)
REG_ICALL("System.IO.MonoIO::get_ConsoleInput()", mscorlib::System::IO::MonoIO::get_ConsoleInput)
REG_ICALL("System.IO.MonoIO::get_ConsoleOutput()", mscorlib::System::IO::MonoIO::get_ConsoleOutput)
REG_ICALL("System.IO.MonoIO::get_DirectorySeparatorChar()", mscorlib::System::IO::MonoIO::get_DirectorySeparatorChar)
REG_ICALL("System.IO.MonoIO::get_PathSeparator()", mscorlib::System::IO::MonoIO::get_PathSeparator)
REG_ICALL("System.IO.MonoIO::get_VolumeSeparatorChar()", mscorlib::System::IO::MonoIO::get_VolumeSeparatorChar)
REG_ICALL("System.IO.MonoIO::GetCurrentDirectory(System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::GetCurrentDirectory)
REG_ICALL("System.IO.MonoIO::GetFileAttributes(System.String,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::GetFileAttributes)
REG_ICALL("System.IO.MonoIO::GetFileStat(System.String,System.IO.MonoIOStat&,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::GetFileStat)
REG_ICALL("System.IO.MonoIO::GetFileSystemEntries(System.String,System.String,System.Int32,System.Int32,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::GetFileSystemEntries)
REG_ICALL("System.IO.MonoIO::GetFileType(System.IntPtr,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::GetFileType)
REG_ICALL("System.IO.MonoIO::GetLength(System.IntPtr,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::GetLength)
REG_ICALL("System.IO.MonoIO::GetTempPath(System.String&)", mscorlib::System::IO::MonoIO::GetTempPath)
REG_ICALL("System.IO.MonoIO::Lock(System.IntPtr,System.Int64,System.Int64,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Lock)
REG_ICALL("System.IO.MonoIO::MoveFile(System.String,System.String,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::MoveFile)
REG_ICALL("System.IO.MonoIO::Open(System.String,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,System.IO.FileOptions,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Open)
REG_ICALL("System.IO.MonoIO::Read(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Read)
REG_ICALL("System.IO.MonoIO::RemoveDirectory(System.String,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::RemoveDirectory)
REG_ICALL("System.IO.MonoIO::ReplaceFile(System.String,System.String,System.String,System.Boolean,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::ReplaceFile)
REG_ICALL("System.IO.MonoIO::Seek(System.IntPtr,System.Int64,System.IO.SeekOrigin,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Seek)
REG_ICALL("System.IO.MonoIO::SetCurrentDirectory(System.String,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::SetCurrentDirectory)
REG_ICALL("System.IO.MonoIO::SetFileAttributes(System.String,System.IO.FileAttributes,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::SetFileAttributes)
REG_ICALL("System.IO.MonoIO::SetFileTime(System.IntPtr,System.Int64,System.Int64,System.Int64,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::SetFileTime)
REG_ICALL("System.IO.MonoIO::SetLength(System.IntPtr,System.Int64,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::SetLength)
REG_ICALL("System.IO.MonoIO::Unlock(System.IntPtr,System.Int64,System.Int64,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Unlock)
REG_ICALL("System.IO.MonoIO::Write(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.IO.MonoIOError&)", mscorlib::System::IO::MonoIO::Write)

// System.IO.Path
REG_ICALL("System.IO.Path::get_temp_path()", mscorlib::System::IO::Path::get_temp_path)

// System.Math
REG_ICALL("System.Math::Acos(System.Double)", mscorlib::System::Math::Acos)
REG_ICALL("System.Math::Asin(System.Double)", mscorlib::System::Math::Asin)
REG_ICALL("System.Math::Atan(System.Double)", mscorlib::System::Math::Atan)
REG_ICALL("System.Math::Atan2(System.Double,System.Double)", mscorlib::System::Math::Atan2)
REG_ICALL("System.Math::Cos(System.Double)", mscorlib::System::Math::Cos)
REG_ICALL("System.Math::Cosh(System.Double)", mscorlib::System::Math::Cosh)
REG_ICALL("System.Math::Exp(System.Double)", mscorlib::System::Math::Exp)
REG_ICALL("System.Math::Floor(System.Double)", mscorlib::System::Math::Floor)
REG_ICALL("System.Math::Log(System.Double)", mscorlib::System::Math::Log)
REG_ICALL("System.Math::Log10(System.Double)", mscorlib::System::Math::Log10)
REG_ICALL("System.Math::Pow(System.Double,System.Double)", mscorlib::System::Math::Pow)
REG_ICALL("System.Math::Round(System.Double)", mscorlib::System::Math::Round)
REG_ICALL("System.Math::Round2(System.Double,System.Int32,System.Boolean)", mscorlib::System::Math::Round2)
REG_ICALL("System.Math::Sin(System.Double)", mscorlib::System::Math::Sin)
REG_ICALL("System.Math::Sinh(System.Double)", mscorlib::System::Math::Sinh)
REG_ICALL("System.Math::Sqrt(System.Double)", mscorlib::System::Math::Sqrt)
REG_ICALL("System.Math::Tan(System.Double)", mscorlib::System::Math::Tan)
REG_ICALL("System.Math::Tanh(System.Double)", mscorlib::System::Math::Tanh)

// System.MonoCustomAttrs
REG_ICALL("System.MonoCustomAttrs::GetCustomAttributesDataInternal(System.Reflection.ICustomAttributeProvider)", mscorlib::System::MonoCustomAttrs::GetCustomAttributesDataInternal)
REG_ICALL("System.MonoCustomAttrs::GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,System.Boolean)", mscorlib::System::MonoCustomAttrs::GetCustomAttributesInternal)
REG_ICALL("System.MonoCustomAttrs::IsDefinedInternal(System.Reflection.ICustomAttributeProvider,System.Type)", mscorlib::System::MonoCustomAttrs::IsDefinedInternal)

// System.MonoEnumInfo
REG_ICALL("System.MonoEnumInfo::get_enum_info(System.Type,System.MonoEnumInfo&)", mscorlib::System::MonoEnumInfo::get_enum_info)

// System.MonoType
REG_ICALL("System.MonoType::get_Assembly()", mscorlib::System::MonoType::get_Assembly)
REG_ICALL("System.MonoType::get_attributes(System.Type)", mscorlib::System::MonoType::get_attributes)
REG_ICALL("System.MonoType::get_BaseType()", mscorlib::System::MonoType::get_BaseType)
REG_ICALL("System.MonoType::get_DeclaringMethod()", mscorlib::System::MonoType::get_DeclaringMethod)
REG_ICALL("System.MonoType::get_DeclaringType()", mscorlib::System::MonoType::get_DeclaringType)
REG_ICALL("System.MonoType::get_IsGenericParameter()", mscorlib::System::MonoType::get_IsGenericParameter)
REG_ICALL("System.MonoType::get_Module()", mscorlib::System::MonoType::get_Module)
REG_ICALL("System.MonoType::get_Name()", mscorlib::System::MonoType::get_Name)
REG_ICALL("System.MonoType::get_Namespace()", mscorlib::System::MonoType::get_Namespace)
REG_ICALL("System.MonoType::GetArrayRank()", mscorlib::System::MonoType::GetArrayRank)
REG_ICALL("System.MonoType::GetConstructors_internal(System.Reflection.BindingFlags,System.Type)", mscorlib::System::MonoType::GetConstructors_internal)
REG_ICALL("System.MonoType::GetCorrespondingInflatedConstructor(System.Reflection.ConstructorInfo)", mscorlib::System::MonoType::GetCorrespondingInflatedMethod)
REG_ICALL("System.MonoType::GetCorrespondingInflatedMethod(System.Reflection.MethodInfo)", mscorlib::System::MonoType::GetCorrespondingInflatedMethod)
REG_ICALL("System.MonoType::GetElementType()", mscorlib::System::MonoType::GetElementType)
REG_ICALL("System.MonoType::GetEvents_internal(System.Reflection.BindingFlags,System.Type)", mscorlib::System::MonoType::GetEvents_internal)
REG_ICALL("System.MonoType::GetField(System.String,System.Reflection.BindingFlags)", mscorlib::System::MonoType::GetField)
REG_ICALL("System.MonoType::GetFields_internal(System.Reflection.BindingFlags,System.Type)", mscorlib::System::MonoType::GetFields_internal)
REG_ICALL("System.MonoType::getFullName(System.Boolean,System.Boolean)", mscorlib::System::MonoType::getFullName)
REG_ICALL("System.MonoType::GetGenericArguments()", mscorlib::System::MonoType::GetGenericArguments)
REG_ICALL("System.MonoType::GetInterfaces()", mscorlib::System::MonoType::GetInterfaces)
REG_ICALL("System.MonoType::GetMethodsByName(System.String,System.Reflection.BindingFlags,System.Boolean,System.Type)", mscorlib::System::MonoType::GetMethodsByName)
REG_ICALL("System.MonoType::GetNestedType(System.String,System.Reflection.BindingFlags)", mscorlib::System::MonoType::GetNestedType)
REG_ICALL("System.MonoType::GetNestedTypes(System.Reflection.BindingFlags)", mscorlib::System::MonoType::GetNestedTypes)
REG_ICALL("System.MonoType::GetPropertiesByName(System.String,System.Reflection.BindingFlags,System.Boolean,System.Type)", mscorlib::System::MonoType::GetPropertiesByName)
REG_ICALL("System.MonoType::InternalGetEvent(System.String,System.Reflection.BindingFlags)", mscorlib::System::MonoType::InternalGetEvent)
REG_ICALL("System.MonoType::IsByRefImpl()", mscorlib::System::MonoType::IsByRefImpl)
REG_ICALL("System.MonoType::IsCOMObjectImpl()", mscorlib::System::MonoType::IsCOMObjectImpl)
REG_ICALL("System.MonoType::IsPointerImpl()", mscorlib::System::MonoType::IsPointerImpl)
REG_ICALL("System.MonoType::IsPrimitiveImpl()", mscorlib::System::MonoType::IsPrimitiveImpl)
REG_ICALL("System.MonoType::type_from_obj(System.MonoType,System.Object)", mscorlib::System::MonoType::type_from_obj)

// System.NumberFormatter
REG_ICALL("System.NumberFormatter::GetFormatterTables(System.UInt64*&,System.Int32*&,System.Char*&,System.Char*&,System.Int64*&,System.Int32*&)", mscorlib::System::NumberFormatter::GetFormatterTables)

// System.Net
REG_ICALL("System.Net.Dns::GetHostByAddr_internal(System.String,System.String&,System.String[]&,System.String[]&)", System::System::Net::Dns::GetHostByAddr)
REG_ICALL("System.Net.Dns::GetHostByName_internal(System.String,System.String&,System.String[]&,System.String[]&)", System::System::Net::Dns::GetHostByName)
REG_ICALL("System.Net.Dns::GetHostName_internal(System.String&)", System::System::Net::Dns::GetHostName)

// System.Net.Sockets
REG_ICALL("System.Net.Sockets.Socket::Accept_internal(System.IntPtr,System.Int32&,System.Boolean)", System::System::Net::Sockets::Socket::Accept)
REG_ICALL("System.Net.Sockets.Socket::Available_internal(System.IntPtr,System.Int32&)", System::System::Net::Sockets::Socket::Available)
REG_ICALL("System.Net.Sockets.Socket::Bind_internal(System.IntPtr,System.Net.SocketAddress,System.Int32&)", System::System::Net::Sockets::Socket::Bind)
REG_ICALL("System.Net.Sockets.Socket::Blocking_internal(System.IntPtr,System.Boolean,System.Int32&)", System::System::Net::Sockets::Socket::Blocking)
REG_ICALL("System.Net.Sockets.Socket::Close_internal(System.IntPtr,System.Int32&)", System::System::Net::Sockets::Socket::Close)
REG_ICALL("System.Net.Sockets.Socket::Connect_internal_real(System.IntPtr,System.Net.SocketAddress,System.Int32&)", System::System::Net::Sockets::Socket::Connect)
REG_ICALL("System.Net.Sockets.Socket::Disconnect_internal(System.IntPtr,System.Boolean,System.Int32&)", System::System::Net::Sockets::Socket::Disconnect)
REG_ICALL("System.Net.Sockets.Socket::GetSocketOption_arr_internal(System.IntPtr,System.Net.Sockets.SocketOptionLevel,System.Net.Sockets.SocketOptionName,System.Byte[]&,System.Int32&)", System::System::Net::Sockets::Socket::GetSocketOptionArray)
REG_ICALL("System.Net.Sockets.Socket::GetSocketOption_obj_internal(System.IntPtr,System.Net.Sockets.SocketOptionLevel,System.Net.Sockets.SocketOptionName,System.Object&,System.Int32&)", System::System::Net::Sockets::Socket::GetSocketOptionObj)
REG_ICALL("System.Net.Sockets.Socket::Listen_internal(System.IntPtr,System.Int32,System.Int32&)", System::System::Net::Sockets::Socket::Listen)
REG_ICALL("System.Net.Sockets.Socket::LocalEndPoint_internal(System.IntPtr,System.Int32&)", System::System::Net::Sockets::Socket::LocalEndPoint)
REG_ICALL("System.Net.Sockets.Socket::Poll_internal", System::System::Net::Sockets::Socket::Poll)
REG_ICALL("System.Net.Sockets.Socket::Receive_internal(System.IntPtr,System.Net.Sockets.Socket/WSABUF[],System.Net.Sockets.SocketFlags,System.Int32&)", System::System::Net::Sockets::Socket::ReceiveArray)
REG_ICALL("System.Net.Sockets.Socket::Receive_internal(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.Net.Sockets.SocketFlags,System.Int32&)", System::System::Net::Sockets::Socket::Receive)
REG_ICALL("System.Net.Sockets.Socket::RecvFrom_internal(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.Net.Sockets.SocketFlags,System.Net.SocketAddress&,System.Int32&)", System::System::Net::Sockets::Socket::RecvFrom)
REG_ICALL("System.Net.Sockets.Socket::RemoteEndPoint_internal(System.IntPtr,System.Int32&)", System::System::Net::Sockets::Socket::RemoteEndPoint)
REG_ICALL("System.Net.Sockets.Socket::Select_internal(System.Net.Sockets.Socket[]&,System.Int32,System.Int32&)", System::System::Net::Sockets::Socket::Select)
REG_ICALL("System.Net.Sockets.Socket::SendFile(System.IntPtr,System.String,System.Byte[],System.Byte[],System.Net.Sockets.TransmitFileOptions)", System::System::Net::Sockets::Socket::SendFile)
REG_ICALL("System.Net.Sockets.Socket::SendTo_internal_real(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.Net.Sockets.SocketFlags,System.Net.SocketAddress,System.Int32&)", System::System::Net::Sockets::Socket::SendTo)
REG_ICALL("System.Net.Sockets.Socket::Send_internal(System.IntPtr,System.Net.Sockets.Socket/WSABUF[],System.Net.Sockets.SocketFlags,System.Int32&)", System::System::Net::Sockets::Socket::SendArray)
REG_ICALL("System.Net.Sockets.Socket::Send_internal(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.Net.Sockets.SocketFlags,System.Int32&)", System::System::Net::Sockets::Socket::Send)
REG_ICALL("System.Net.Sockets.Socket::SetSocketOption_internal(System.IntPtr,System.Net.Sockets.SocketOptionLevel,System.Net.Sockets.SocketOptionName,System.Object,System.Byte[],System.Int32,System.Int32&)", System::System::Net::Sockets::Socket::SetSocketOption)
REG_ICALL("System.Net.Sockets.Socket::Shutdown_internal(System.IntPtr,System.Net.Sockets.SocketShutdown,System.Int32&)", System::System::Net::Sockets::Socket::Shutdown)
REG_ICALL("System.Net.Sockets.Socket::Socket_internal(System.Net.Sockets.AddressFamily,System.Net.Sockets.SocketType,System.Net.Sockets.ProtocolType,System.Int32&)", System::System::Net::Sockets::Socket::Socket_internal)
REG_ICALL("System.Net.Sockets.Socket::WSAIoctl(System.IntPtr,System.Int32,System.Byte[],System.Byte[],System.Int32&)", System::System::Net::Sockets::Socket::WSAIoctl)
REG_ICALL("System.Net.Sockets.SocketException::WSAGetLastError_internal", System::System::Net::Sockets::SocketException::WSAGetLastError)

// System.Object
REG_ICALL("System.Object::GetType()", mscorlib::System::Object::GetType)
REG_ICALL("System.Object::InternalGetHashCode(System.Object)", mscorlib::System::Object::InternalGetHashCode)
REG_ICALL("System.Object::MemberwiseClone()", mscorlib::System::Object::MemberwiseClone)
REG_ICALL("System.Object::obj_address()", mscorlib::System::Object::obj_address)

// System.Reflection.Assembly
REG_ICALL("System.Reflection.Assembly::FillName(System.Reflection.Assembly,System.Reflection.AssemblyName)", mscorlib::System::Reflection::Assembly::FillName)
REG_ICALL("System.Reflection.Assembly::get_code_base(System.Boolean)", mscorlib::System::Reflection::Assembly::get_code_base)
REG_ICALL("System.Reflection.Assembly::get_EntryPoint()", mscorlib::System::Reflection::Assembly::get_EntryPoint)
REG_ICALL("System.Reflection.Assembly::get_fullname()", mscorlib::System::Reflection::Assembly::get_fullname)
REG_ICALL("System.Reflection.Assembly::get_global_assembly_cache()", mscorlib::System::Reflection::Assembly::get_global_assembly_cache)
REG_ICALL("System.Reflection.Assembly::get_location()", mscorlib::System::Reflection::Assembly::get_location)
REG_ICALL("System.Reflection.Assembly::get_ReflectionOnly()", mscorlib::System::Reflection::Assembly::get_ReflectionOnly)
REG_ICALL("System.Reflection.Assembly::GetCallingAssembly()", mscorlib::System::Reflection::Assembly::GetCallingAssembly)
REG_ICALL("System.Reflection.Assembly::GetEntryAssembly()", mscorlib::System::Reflection::Assembly::GetEntryAssembly)
REG_ICALL("System.Reflection.Assembly::GetExecutingAssembly()", mscorlib::System::Reflection::Assembly::GetExecutingAssembly)
REG_ICALL("System.Reflection.Assembly::GetFilesInternal(System.String,System.Boolean)", mscorlib::System::Reflection::Assembly::GetFilesInternal)
REG_ICALL("System.Reflection.Assembly::GetManifestModuleInternal()", mscorlib::System::Reflection::Assembly::GetManifestModuleInternal)
REG_ICALL("System.Reflection.Assembly::GetManifestResourceInfoInternal(System.String,System.Reflection.ManifestResourceInfo)", mscorlib::System::Reflection::Assembly::GetManifestResourceInfoInternal)
REG_ICALL("System.Reflection.Assembly::GetManifestResourceInternal(System.String,System.Int32&,System.Reflection.Module&)", mscorlib::System::Reflection::Assembly::GetManifestResourceInternal)
REG_ICALL("System.Reflection.Assembly::GetManifestResourceNames()", mscorlib::System::Reflection::Assembly::GetManifestResourceNames)
REG_ICALL("System.Reflection.Assembly::GetModulesInternal()", mscorlib::System::Reflection::Assembly::GetModulesInternal)
REG_ICALL("System.Reflection.Assembly::GetNamespaces()", mscorlib::System::Reflection::Assembly::GetNamespaces)
REG_ICALL("System.Reflection.Assembly::GetReferencedAssemblies()", mscorlib::System::Reflection::Assembly::GetReferencedAssemblies)
REG_ICALL("System.Reflection.Assembly::GetTypes(System.Boolean)", mscorlib::System::Reflection::Assembly::GetTypes)
REG_ICALL("System.Reflection.Assembly::InternalGetAssemblyName(System.String,System.Reflection.AssemblyName)", mscorlib::System::Reflection::Assembly::InternalGetAssemblyName)
REG_ICALL("System.Reflection.Assembly::InternalGetType(System.Reflection.Module,System.String,System.Boolean,System.Boolean)", mscorlib::System::Reflection::Assembly::InternalGetType)
REG_ICALL("System.Reflection.Assembly::InternalImageRuntimeVersion()", mscorlib::System::Reflection::Assembly::InternalImageRuntimeVersion)
REG_ICALL("System.Reflection.Assembly::load_with_partial_name(System.String,System.Security.Policy.Evidence)", mscorlib::System::Reflection::Assembly::load_with_partial_name)
REG_ICALL("System.Reflection.Assembly::LoadFrom(System.String,System.Boolean)", mscorlib::System::Reflection::Assembly::LoadFrom)
REG_ICALL("System.Reflection.Assembly::LoadPermissions(System.Reflection.Assembly,System.IntPtr&,System.Int32&,System.IntPtr&,System.Int32&,System.IntPtr&,System.Int32&)", mscorlib::System::Reflection::Assembly::LoadPermissions)
REG_ICALL("System.Reflection.Assembly::MonoDebugger_GetMethodToken(System.Reflection.MethodBase)", mscorlib::System::Reflection::Assembly::MonoDebugger_GetMethodToken)

// System.Reflection.AssemblyName
REG_ICALL("System.Reflection.AssemblyName::ParseName(System.Reflection.AssemblyName,System.String)", mscorlib::System::Reflection::AssemblyName::ParseName)

// System.Reflection.Emit.AssemblyBuilder
REG_ICALL("System.Reflection.Emit.AssemblyBuilder::basic_init(System.Reflection.Emit.AssemblyBuilder)", mscorlib::System::Reflection::Emit::AssemblyBuilder::basic_init)
REG_ICALL("System.Reflection.Emit.AssemblyBuilder::InternalAddModule(System.String)", mscorlib::System::Reflection::Emit::AssemblyBuilder::InternalAddModule)

// System.Reflection.Emit.CustomAttributeBuilder
REG_ICALL("System.Reflection.Emit.CustomAttributeBuilder::GetBlob(System.Reflection.Assembly,System.Reflection.ConstructorInfo,System.Object[],System.Reflection.PropertyInfo[],System.Object[],System.Reflection.FieldInfo[],System.Object[])", mscorlib::System::Reflection::Emit::CustomAttributeBuilder::GetBlob)

// System.Reflection.Emit.DerivedType
REG_ICALL("System.Reflection.Emit.DerivedType::create_unmanaged_type(System.Type)", mscorlib::System::Reflection::Emit::DerivedType::create_unmanaged_type)

// System.Reflection.Emit.DynamicMethod
REG_ICALL("System.Reflection.Emit.DynamicMethod::create_dynamic_method(System.Reflection.Emit.DynamicMethod)", mscorlib::System::Reflection::Emit::DynamicMethod::create_dynamic_method)
REG_ICALL("System.Reflection.Emit.DynamicMethod::destroy_dynamic_method(System.Reflection.Emit.DynamicMethod)", mscorlib::System::Reflection::Emit::DynamicMethod::destroy_dynamic_method)

// System.Reflection.Emit.EnumBuilder
REG_ICALL("System.Reflection.Emit.EnumBuilder::setup_enum_type(System.Type)", mscorlib::System::Reflection::Emit::EnumBuilder::setup_enum_type)

// System.Reflection.Emit.GenericTypeParameterBuilder
REG_ICALL("System.Reflection.Emit.GenericTypeParameterBuilder::initialize()", mscorlib::System::Reflection::Emit::GenericTypeParameterBuilder::initialize)

// System.Reflection.Emit.MethodBuilder
REG_ICALL("System.Reflection.Emit.MethodBuilder::MakeGenericMethod(System.Type[])", mscorlib::System::Reflection::Emit::MethodBuilder::MakeGenericMethod)

// System.Reflection.Emit.ModuleBuilder
REG_ICALL("System.Reflection.Emit.ModuleBuilder::basic_init(System.Reflection.Emit.ModuleBuilder)", mscorlib::System::Reflection::Emit::ModuleBuilder::basic_init)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::build_metadata(System.Reflection.Emit.ModuleBuilder)", mscorlib::System::Reflection::Emit::ModuleBuilder::build_metadata)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::create_modified_type(System.Reflection.Emit.TypeBuilder,System.String)", mscorlib::System::Reflection::Emit::ModuleBuilder::create_modified_type)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::getMethodToken(System.Reflection.Emit.ModuleBuilder,System.Reflection.MethodInfo,System.Type[])", mscorlib::System::Reflection::Emit::ModuleBuilder::getMethodToken)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::getToken(System.Reflection.Emit.ModuleBuilder,System.Object)", mscorlib::System::Reflection::Emit::ModuleBuilder::getToken)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::getUSIndex(System.Reflection.Emit.ModuleBuilder,System.String)", mscorlib::System::Reflection::Emit::ModuleBuilder::getUSIndex)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::RegisterToken(System.Object,System.Int32)", mscorlib::System::Reflection::Emit::ModuleBuilder::RegisterToken)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::set_wrappers_type(System.Reflection.Emit.ModuleBuilder,System.Type)", mscorlib::System::Reflection::Emit::ModuleBuilder::set_wrappers_type)
REG_ICALL("System.Reflection.Emit.ModuleBuilder::WriteToFile(System.IntPtr)", mscorlib::System::Reflection::Emit::ModuleBuilder::WriteToFile)

// System.Reflection.Emit.SignatureHelper
REG_ICALL("System.Reflection.Emit.SignatureHelper::get_signature_field()", mscorlib::System::Reflection::Emit::SignatureHelper::get_signature_field)
REG_ICALL("System.Reflection.Emit.SignatureHelper::get_signature_local()", mscorlib::System::Reflection::Emit::SignatureHelper::get_signature_local)

// System.Reflection.Emit.TypeBuilder
REG_ICALL("System.Reflection.Emit.TypeBuilder::create_generic_class()", mscorlib::System::Reflection::Emit::TypeBuilder::create_generic_class)
REG_ICALL("System.Reflection.Emit.TypeBuilder::create_internal_class(System.Reflection.Emit.TypeBuilder)", mscorlib::System::Reflection::Emit::TypeBuilder::create_internal_class)
REG_ICALL("System.Reflection.Emit.TypeBuilder::create_runtime_class(System.Reflection.Emit.TypeBuilder)", mscorlib::System::Reflection::Emit::TypeBuilder::create_runtime_class)
REG_ICALL("System.Reflection.Emit.TypeBuilder::get_event_info(System.Reflection.Emit.EventBuilder)", mscorlib::System::Reflection::Emit::TypeBuilder::get_event_info)
REG_ICALL("System.Reflection.Emit.TypeBuilder::get_IsGenericParameter()", mscorlib::System::Reflection::Emit::TypeBuilder::get_IsGenericParameter)
REG_ICALL("System.Reflection.Emit.TypeBuilder::setup_generic_class()", mscorlib::System::Reflection::Emit::TypeBuilder::setup_generic_class)
REG_ICALL("System.Reflection.Emit.TypeBuilder::setup_internal_class(System.Reflection.Emit.TypeBuilder)", mscorlib::System::Reflection::Emit::TypeBuilder::setup_internal_class)

// System.Reflection.FieldInfo
REG_ICALL("System.Reflection.FieldInfo::GetTypeModifiers(System.Boolean)", mscorlib::System::Reflection::FieldInfo::GetTypeModifiers)
REG_ICALL("System.Reflection.FieldInfo::GetUnmanagedMarshal()", mscorlib::System::Reflection::FieldInfo::GetUnmanagedMarshal)
REG_ICALL("System.Reflection.FieldInfo::internal_from_handle_type(System.IntPtr,System.IntPtr)", mscorlib::System::Reflection::FieldInfo::internal_from_handle_type)

// System.Reflection.MemberInfo
REG_ICALL("System.Reflection.MemberInfo::get_MetadataToken()", mscorlib::System::Reflection::MemberInfo::get_MetadataToken)

// System.Reflection.MethodBase
REG_ICALL("System.Reflection.MethodBase::GetCurrentMethod()", mscorlib::System::Reflection::MethodBase::GetCurrentMethod)
REG_ICALL("System.Reflection.MethodBase::GetMethodBodyInternal(System.IntPtr)", mscorlib::System::Reflection::MethodBase::GetMethodBodyInternal)
REG_ICALL("System.Reflection.MethodBase::GetMethodFromHandleInternalType(System.IntPtr,System.IntPtr)", mscorlib::System::Reflection::MethodBase::GetMethodFromHandleInternalType)

// System.Reflection.Module
REG_ICALL("System.Reflection.Module::get_MetadataToken()", mscorlib::System::Reflection::Module::get_MetadataToken)
REG_ICALL("System.Reflection.Module::GetGlobalType()", mscorlib::System::Reflection::Module::GetGlobalType)
REG_ICALL("System.Reflection.Module::GetGuidInternal()", mscorlib::System::Reflection::Module::GetGuidInternal)
REG_ICALL("System.Reflection.Module::GetHINSTANCE()", mscorlib::System::Reflection::Module::GetHINSTANCE)
REG_ICALL("System.Reflection.Module::GetMDStreamVersion(System.IntPtr)", mscorlib::System::Reflection::Module::GetMDStreamVersion)
REG_ICALL("System.Reflection.Module::GetPEKind(System.IntPtr,System.Reflection.PortableExecutableKinds&,System.Reflection.ImageFileMachine&)", mscorlib::System::Reflection::Module::GetPEKind)
REG_ICALL("System.Reflection.Module::InternalGetTypes()", mscorlib::System::Reflection::Module::InternalGetTypes)
REG_ICALL("System.Reflection.Module::ResolveFieldToken(System.IntPtr,System.Int32,System.IntPtr[],System.IntPtr[],System.Reflection.ResolveTokenError&)", mscorlib::System::Reflection::Module::ResolveFieldToken)
REG_ICALL("System.Reflection.Module::ResolveMemberToken(System.IntPtr,System.Int32,System.IntPtr[],System.IntPtr[],System.Reflection.ResolveTokenError&)", mscorlib::System::Reflection::Module::ResolveMemberToken)
REG_ICALL("System.Reflection.Module::ResolveMethodToken(System.IntPtr,System.Int32,System.IntPtr[],System.IntPtr[],System.Reflection.ResolveTokenError&)", mscorlib::System::Reflection::Module::ResolveMethodToken)
REG_ICALL("System.Reflection.Module::ResolveSignature(System.IntPtr,System.Int32,System.Reflection.ResolveTokenError&)", mscorlib::System::Reflection::Module::ResolveSignature)
REG_ICALL("System.Reflection.Module::ResolveStringToken(System.IntPtr,System.Int32,System.Reflection.ResolveTokenError&)", mscorlib::System::Reflection::Module::ResolveStringToken)
REG_ICALL("System.Reflection.Module::ResolveTypeToken(System.IntPtr,System.Int32,System.IntPtr[],System.IntPtr[],System.Reflection.ResolveTokenError&)", mscorlib::System::Reflection::Module::ResolveTypeToken)

// System.Reflection.MonoCMethod
REG_ICALL("System.Reflection.MonoCMethod::InternalInvoke(System.Object,System.Object[],System.Exception&)", mscorlib::System::Reflection::MonoMethod::InternalInvoke)

// System.Reflection.MonoEventInfo
REG_ICALL("System.Reflection.MonoEventInfo::get_event_info(System.Reflection.MonoEvent,System.Reflection.MonoEventInfo&)", mscorlib::System::Reflection::MonoEventInfo::get_event_info)

// System.Reflection.MonoField
REG_ICALL("System.Reflection.MonoField::GetFieldOffset()", mscorlib::System::Reflection::MonoField::GetFieldOffset)
REG_ICALL("System.Reflection.MonoField::GetParentType(System.Boolean)", mscorlib::System::Reflection::MonoField::GetParentType)
REG_ICALL("System.Reflection.MonoField::GetRawConstantValue()", mscorlib::System::Reflection::MonoField::GetRawConstantValue)
REG_ICALL("System.Reflection.MonoField::GetValueInternal(System.Object)", mscorlib::System::Reflection::MonoField::GetValueInternal)
REG_ICALL("System.Reflection.MonoField::SetValueInternal(System.Reflection.FieldInfo,System.Object,System.Object)", mscorlib::System::Reflection::MonoField::SetValueInternal)

// System.Reflection.MonoGenericClass
REG_ICALL("System.Reflection.MonoGenericClass::initialize(System.Reflection.MethodInfo[],System.Reflection.ConstructorInfo[],System.Reflection.FieldInfo[],System.Reflection.PropertyInfo[],System.Reflection.EventInfo[])", mscorlib::System::Reflection::MonoGenericClass::initialize)

// System.Reflection.MonoGenericCMethod
REG_ICALL("System.Reflection.MonoGenericCMethod::get_ReflectedType()", mscorlib::System::Reflection::MonoGenericCMethod::get_ReflectedType)

// System.Reflection.MonoGenericMethod
REG_ICALL("System.Reflection.MonoGenericMethod::get_ReflectedType()", mscorlib::System::Reflection::MonoGenericMethod::get_ReflectedType)

// System.Reflection.MonoMethod
REG_ICALL("System.Reflection.MonoMethod::get_base_definition(System.Reflection.MonoMethod)", mscorlib::System::Reflection::MonoMethod::get_base_definition)
REG_ICALL("System.Reflection.MonoMethod::get_IsGenericMethod()", mscorlib::System::Reflection::MonoMethod::get_IsGenericMethod)
REG_ICALL("System.Reflection.MonoMethod::get_IsGenericMethodDefinition()", mscorlib::System::Reflection::MonoMethod::get_IsGenericMethodDefinition)
REG_ICALL("System.Reflection.MonoMethod::get_name(System.Reflection.MethodBase)", mscorlib::System::Reflection::MonoMethod::get_name)
REG_ICALL("System.Reflection.MonoMethod::GetDllImportAttribute(System.IntPtr)", mscorlib::System::Reflection::MonoMethod::GetDllImportAttribute)
REG_ICALL("System.Reflection.MonoMethod::GetGenericArguments()", mscorlib::System::Reflection::MonoMethod::GetGenericArguments)
REG_ICALL("System.Reflection.MonoMethod::GetGenericMethodDefinition_impl()", mscorlib::System::Reflection::MonoMethod::GetGenericMethodDefinition_impl)
REG_ICALL("System.Reflection.MonoMethod::InternalInvoke(System.Object,System.Object[],System.Exception&)", mscorlib::System::Reflection::MonoMethod::InternalInvoke)
REG_ICALL("System.Reflection.MonoMethod::MakeGenericMethod_impl(System.Type[])", mscorlib::System::Reflection::MonoMethod::MakeGenericMethod_impl)

// System.Reflection.MonoMethodInfo
REG_ICALL("System.Reflection.MonoMethodInfo::get_method_info(System.IntPtr,System.Reflection.MonoMethodInfo&)", mscorlib::System::Reflection::MonoMethodInfo::get_method_info)
REG_ICALL("System.Reflection.MonoMethodInfo::get_parameter_info(System.IntPtr,System.Reflection.MemberInfo)", mscorlib::System::Reflection::MonoMethodInfo::get_parameter_info)
REG_ICALL("System.Reflection.MonoMethodInfo::get_retval_marshal(System.IntPtr)", mscorlib::System::Reflection::MonoMethodInfo::get_retval_marshal)

// System.Reflection.MonoPropertyInfo
REG_ICALL("System.Reflection.MonoPropertyInfo::get_property_info(System.Reflection.MonoProperty,System.Reflection.MonoPropertyInfo&,System.Reflection.PInfo)", mscorlib::System::Reflection::MonoPropertyInfo::get_property_info)
REG_ICALL("System.Reflection.MonoPropertyInfo::GetTypeModifiers(System.Reflection.MonoProperty,System.Boolean)", mscorlib::System::Reflection::MonoPropertyInfo::GetTypeModifiers)

// System.Reflection.ParameterInfo
REG_ICALL("System.Reflection.ParameterInfo::GetMetadataToken()", mscorlib::System::Reflection::ParameterInfo::GetMetadataToken)
REG_ICALL("System.Reflection.ParameterInfo::GetTypeModifiers(System.Boolean)", mscorlib::System::Reflection::ParameterInfo::GetTypeModifiers)

// System.Runtime.CompilerServices.RuntimeHelpers
REG_ICALL("System.Runtime.CompilerServices.RuntimeHelpers::get_OffsetToStringData()", mscorlib::System::Runtime::CompilerServices::RuntimeHelpers::get_OffsetToStringData)
REG_ICALL("System.Runtime.CompilerServices.RuntimeHelpers::GetObjectValue(System.Object)", mscorlib::System::Runtime::CompilerServices::RuntimeHelpers::GetObjectValue)
REG_ICALL("System.Runtime.CompilerServices.RuntimeHelpers::InitializeArray(System.Array,System.IntPtr)", mscorlib::System::Runtime::CompilerServices::RuntimeHelpers::InitializeArray)
REG_ICALL("System.Runtime.CompilerServices.RuntimeHelpers::RunClassConstructor(System.IntPtr)", mscorlib::System::Runtime::CompilerServices::RuntimeHelpers::RunClassConstructor)
REG_ICALL("System.Runtime.CompilerServices.RuntimeHelpers::RunModuleConstructor(System.IntPtr)", mscorlib::System::Runtime::CompilerServices::RuntimeHelpers::RunModuleConstructor)

// System.Runtime.InteropServices.GCHandle
REG_ICALL("System.Runtime.InteropServices.GCHandle::CheckCurrentDomain(System.Int32)", mscorlib::System::Runtime::InteropServices::GCHandle::CheckCurrentDomain)
REG_ICALL("System.Runtime.InteropServices.GCHandle::FreeHandle(System.Int32)", mscorlib::System::Runtime::InteropServices::GCHandle::FreeHandle)
REG_ICALL("System.Runtime.InteropServices.GCHandle::GetAddrOfPinnedObject(System.Int32)", mscorlib::System::Runtime::InteropServices::GCHandle::GetAddrOfPinnedObject)
REG_ICALL("System.Runtime.InteropServices.GCHandle::GetTarget(System.Int32)", mscorlib::System::Runtime::InteropServices::GCHandle::GetTarget)
REG_ICALL("System.Runtime.InteropServices.GCHandle::GetTargetHandle(System.Object,System.Int32,System.Runtime.InteropServices.GCHandleType)", mscorlib::System::Runtime::InteropServices::GCHandle::GetTargetHandle)

// System.Runtime.InteropServices.Marshal
REG_ICALL("System.Runtime.InteropServices.Marshal::AddRefInternal(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::AddRefInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::AllocCoTaskMem(System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::AllocCoTaskMem)
REG_ICALL("System.Runtime.InteropServices.Marshal::AllocHGlobal(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::AllocHGlobal)
REG_ICALL("System.Runtime.InteropServices.Marshal::copy_from_unmanaged(System.IntPtr,System.Int32,System.Array,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::copy_from_unmanaged)
REG_ICALL("System.Runtime.InteropServices.Marshal::copy_to_unmanaged(System.Array,System.Int32,System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::copy_to_unmanaged)
REG_ICALL("System.Runtime.InteropServices.Marshal::DestroyStructure(System.IntPtr,System.Type)", mscorlib::System::Runtime::InteropServices::Marshal::DestroyStructure)
REG_ICALL("System.Runtime.InteropServices.Marshal::FreeBSTR(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::FreeBSTR)
REG_ICALL("System.Runtime.InteropServices.Marshal::FreeCoTaskMem(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::FreeCoTaskMem)
REG_ICALL("System.Runtime.InteropServices.Marshal::FreeHGlobal(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::FreeHGlobal)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetCCW(System.Object,System.Type)", mscorlib::System::Runtime::InteropServices::Marshal::GetCCW)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetComSlotForMethodInfoInternal(System.Reflection.MemberInfo)", mscorlib::System::Runtime::InteropServices::Marshal::GetComSlotForMethodInfoInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetDelegateForFunctionPointerInternal(System.IntPtr,System.Type)", mscorlib::System::Runtime::InteropServices::Marshal::GetDelegateForFunctionPointerInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetFunctionPointerForDelegateInternal(System.Delegate)", mscorlib::System::Runtime::InteropServices::Marshal::GetFunctionPointerForDelegateInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetIDispatchForObjectInternal(System.Object)", mscorlib::System::Runtime::InteropServices::Marshal::GetIDispatchForObjectInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetIUnknownForObjectInternal(System.Object)", mscorlib::System::Runtime::InteropServices::Marshal::GetIUnknownForObjectInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetLastWin32Error()", mscorlib::System::Runtime::InteropServices::Marshal::GetLastWin32Error)
REG_ICALL("System.Runtime.InteropServices.Marshal::GetObjectForCCW(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::GetObjectForCCW)
REG_ICALL("System.Runtime.InteropServices.Marshal::IsComObject(System.Object)", mscorlib::System::Runtime::InteropServices::Marshal::IsComObject)
REG_ICALL("System.Runtime.InteropServices.Marshal::OffsetOf(System.Type,System.String)", mscorlib::System::Runtime::InteropServices::Marshal::OffsetOf)
REG_ICALL("System.Runtime.InteropServices.Marshal::Prelink(System.Reflection.MethodInfo)", mscorlib::System::Runtime::InteropServices::Marshal::Prelink)
REG_ICALL("System.Runtime.InteropServices.Marshal::PrelinkAll(System.Type)", mscorlib::System::Runtime::InteropServices::Marshal::PrelinkAll)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStringAnsi(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStringAnsi_mscorlib_System_String_mscorlib_System_IntPtr)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStringAnsi(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStringAnsi_mscorlib_System_String_mscorlib_System_IntPtr_mscorlib_System_Int32)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStringBSTR(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStringBSTR)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStringUni(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStringUni_mscorlib_System_String_mscorlib_System_IntPtr)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStringUni(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStringUni_mscorlib_System_String_mscorlib_System_IntPtr_mscorlib_System_Int32)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStructure(System.IntPtr,System.Object)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStructureObject)
REG_ICALL("System.Runtime.InteropServices.Marshal::PtrToStructure(System.IntPtr,System.Type)", mscorlib::System::Runtime::InteropServices::Marshal::PtrToStructure)
REG_ICALL("System.Runtime.InteropServices.Marshal::QueryInterfaceInternal(System.IntPtr,System.Guid&,System.IntPtr&)", mscorlib::System::Runtime::InteropServices::Marshal::QueryInterfaceInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReadByte(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::ReadByte)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReadInt16(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::ReadInt16)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReadInt32(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::ReadInt32)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReadInt64(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::ReadInt64)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReadIntPtr(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::ReadIntPtr)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReAllocCoTaskMem(System.IntPtr,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::ReAllocCoTaskMem)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReAllocHGlobal(System.IntPtr,System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::ReAllocHGlobal)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReleaseComObjectInternal(System.Object)", mscorlib::System::Runtime::InteropServices::Marshal::ReleaseComObjectInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::ReleaseInternal(System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::ReleaseInternal)
REG_ICALL("System.Runtime.InteropServices.Marshal::SizeOf(System.Type)", mscorlib::System::Runtime::InteropServices::Marshal::SizeOf)
REG_ICALL("System.Runtime.InteropServices.Marshal::StringToBSTR(System.String)", mscorlib::System::Runtime::InteropServices::Marshal::StringToBSTR)
REG_ICALL("System.Runtime.InteropServices.Marshal::StringToHGlobalAnsi(System.String)", mscorlib::System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi)
REG_ICALL("System.Runtime.InteropServices.Marshal::StringToHGlobalUni(System.String)", mscorlib::System::Runtime::InteropServices::Marshal::StringToHGlobalUni)
REG_ICALL("System.Runtime.InteropServices.Marshal::StructureToPtr(System.Object,System.IntPtr,System.Boolean)", mscorlib::System::Runtime::InteropServices::Marshal::StructureToPtr)
REG_ICALL("System.Runtime.InteropServices.Marshal::UnsafeAddrOfPinnedArrayElement(System.Array,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::UnsafeAddrOfPinnedArrayElement)
REG_ICALL("System.Runtime.InteropServices.Marshal::WriteByte(System.IntPtr,System.Int32,System.Byte)", mscorlib::System::Runtime::InteropServices::Marshal::WriteByte)
REG_ICALL("System.Runtime.InteropServices.Marshal::WriteInt16(System.IntPtr,System.Int32,System.Char)", mscorlib::System::Runtime::InteropServices::Marshal::WriteInt16)
REG_ICALL("System.Runtime.InteropServices.Marshal::WriteInt16(System.IntPtr,System.Int32,System.Int16)", mscorlib::System::Runtime::InteropServices::Marshal::WriteInt16)
REG_ICALL("System.Runtime.InteropServices.Marshal::WriteInt32(System.IntPtr,System.Int32,System.Int32)", mscorlib::System::Runtime::InteropServices::Marshal::WriteInt32)
REG_ICALL("System.Runtime.InteropServices.Marshal::WriteInt64(System.IntPtr,System.Int32,System.Int64)", mscorlib::System::Runtime::InteropServices::Marshal::WriteInt64)
REG_ICALL("System.Runtime.InteropServices.Marshal::WriteIntPtr(System.IntPtr,System.Int32,System.IntPtr)", mscorlib::System::Runtime::InteropServices::Marshal::WriteIntPtr)

// System.Runtime.Remoting.Activation.ActivationServices
REG_ICALL("System.Runtime.Remoting.Activation.ActivationServices::AllocateUninitializedClassInstance(System.Type)", mscorlib::System::Runtime::Remoting::Activation::ActivationServices::AllocateUninitializedClassInstance)
REG_ICALL("System.Runtime.Remoting.Activation.ActivationServices::EnableProxyActivation(System.Type,System.Boolean)", mscorlib::System::Runtime::Remoting::Activation::ActivationServices::EnableProxyActivation)

// System.Runtime.Remoting.Messaging.MonoMethodMessage
REG_ICALL("System.Runtime.Remoting.Messaging.MonoMethodMessage::InitMessage(System.Reflection.MonoMethod,System.Object[])", mscorlib::System::Runtime::Remoting::Messaging::MonoMethodMessage::InitMessage)

// System.Runtime.Remoting.Proxies.RealProxy
REG_ICALL("System.Runtime.Remoting.Proxies.RealProxy::InternalGetProxyType(System.Object)", mscorlib::System::Runtime::Remoting::Proxies::RealProxy::InternalGetProxyType)
REG_ICALL("System.Runtime.Remoting.Proxies.RealProxy::InternalGetTransparentProxy(System.String)", mscorlib::System::Runtime::Remoting::Proxies::RealProxy::InternalGetTransparentProxy)

// System.Runtime.Remoting.RemotingServices
REG_ICALL("System.Runtime.Remoting.RemotingServices::GetVirtualMethod(System.Type,System.Reflection.MethodBase)", mscorlib::System::Runtime::Remoting::RemotingServices::GetVirtualMethod)
REG_ICALL("System.Runtime.Remoting.RemotingServices::InternalExecute(System.Reflection.MethodBase,System.Object,System.Object[],System.Object[]&)", mscorlib::System::Runtime::Remoting::RemotingServices::InternalExecute)
REG_ICALL("System.Runtime.Remoting.RemotingServices::IsTransparentProxy(System.Object)", mscorlib::System::Runtime::Remoting::RemotingServices::IsTransparentProxy)

// System.RuntimeMethodHandle
REG_ICALL("System.RuntimeMethodHandle::GetFunctionPointer(System.IntPtr)", mscorlib::System::RuntimeMethodHandle::GetFunctionPointer)

// System.Security.Cryptography.RNGCryptoServiceProvider
REG_ICALL("System.Security.Cryptography.RNGCryptoServiceProvider::RngClose(System.IntPtr)", mscorlib::System::Security::Cryptography::RNGCryptoServiceProvider::RngClose)
REG_ICALL("System.Security.Cryptography.RNGCryptoServiceProvider::RngGetBytes(System.IntPtr,System.Byte[])", mscorlib::System::Security::Cryptography::RNGCryptoServiceProvider::RngGetBytes)
REG_ICALL("System.Security.Cryptography.RNGCryptoServiceProvider::RngInitialize(System.Byte[])", mscorlib::System::Security::Cryptography::RNGCryptoServiceProvider::RngInitialize)
REG_ICALL("System.Security.Cryptography.RNGCryptoServiceProvider::RngOpen()", mscorlib::System::Security::Cryptography::RNGCryptoServiceProvider::RngOpen)

// System.Security.Policy.Evidence
REG_ICALL("System.Security.Policy.Evidence::IsAuthenticodePresent(System.Reflection.Assembly)", mscorlib::System::Security::Policy::Evidence::IsAuthenticodePresent)

// System.Security.Principal.WindowsIdentity
REG_ICALL("System.Security.Principal.WindowsIdentity::_GetRoles(System.IntPtr)", mscorlib::System::Security::Principal::WindowsIdentity::_GetRoles)
REG_ICALL("System.Security.Principal.WindowsIdentity::GetCurrentToken()", mscorlib::System::Security::Principal::WindowsIdentity::GetCurrentToken)
REG_ICALL("System.Security.Principal.WindowsIdentity::GetTokenName(System.IntPtr)", mscorlib::System::Security::Principal::WindowsIdentity::GetTokenName)
REG_ICALL("System.Security.Principal.WindowsIdentity::GetUserToken(System.String)", mscorlib::System::Security::Principal::WindowsIdentity::GetUserToken)

// System.Security.Principal.WindowsImpersonationContext
REG_ICALL("System.Security.Principal.WindowsImpersonationContext::CloseToken(System.IntPtr)", mscorlib::System::Security::Principal::WindowsImpersonationContext::CloseToken)
REG_ICALL("System.Security.Principal.WindowsImpersonationContext::DuplicateToken(System.IntPtr)", mscorlib::System::Security::Principal::WindowsImpersonationContext::DuplicateToken)
REG_ICALL("System.Security.Principal.WindowsImpersonationContext::RevertToSelf()", mscorlib::System::Security::Principal::WindowsImpersonationContext::RevertToSelf)
REG_ICALL("System.Security.Principal.WindowsImpersonationContext::SetCurrentToken(System.IntPtr)", mscorlib::System::Security::Principal::WindowsImpersonationContext::SetCurrentToken)

// System.Security.Principal.WindowsPrincipal
REG_ICALL("System.Security.Principal.WindowsPrincipal::IsMemberOfGroupId(System.IntPtr,System.IntPtr)", mscorlib::System::Security::Principal::WindowsPrincipal::IsMemberOfGroupId)
REG_ICALL("System.Security.Principal.WindowsPrincipal::IsMemberOfGroupName(System.IntPtr,System.String)", mscorlib::System::Security::Principal::WindowsPrincipal::IsMemberOfGroupName)

// System.Security.SecurityFrame
REG_ICALL("System.Security.SecurityFrame::_GetSecurityFrame(System.Int32)", mscorlib::System::Security::SecurityFrame::_GetSecurityFrame)
REG_ICALL("System.Security.SecurityFrame::_GetSecurityStack(System.Int32)", mscorlib::System::Security::SecurityFrame::_GetSecurityStack)

// System.Security.SecurityManager
REG_ICALL("System.Security.SecurityManager::get_CheckExecutionRights()", mscorlib::System::Security::SecurityManager::get_CheckExecutionRights)
REG_ICALL("System.Security.SecurityManager::get_SecurityEnabled()", mscorlib::System::Security::SecurityManager::get_SecurityEnabled)
REG_ICALL("System.Security.SecurityManager::GetLinkDemandSecurity(System.Reflection.MethodBase,System.Security.RuntimeDeclSecurityActions*,System.Security.RuntimeDeclSecurityActions*)", mscorlib::System::Security::SecurityManager::GetLinkDemandSecurity)
REG_ICALL("System.Security.SecurityManager::set_CheckExecutionRights(System.Boolean)", mscorlib::System::Security::SecurityManager::set_CheckExecutionRights)
REG_ICALL("System.Security.SecurityManager::set_SecurityEnabled(System.Boolean)", mscorlib::System::Security::SecurityManager::set_SecurityEnabled)

// 
REG_ICALL("System.String::.ctor(System.Char*)", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.Char*,System.Int32,System.Int32)", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.Char,System.Int32)", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.Char[])", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.Char[],System.Int32,System.Int32)", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.SByte*)", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.SByte*,System.Int32,System.Int32)", mscorlib::System::String::RedirectToCreateString)
REG_ICALL("System.String::.ctor(System.SByte*,System.Int32,System.Int32,System.Text.Encoding)", mscorlib::System::String::RedirectToCreateString)

// System.String
REG_ICALL("System.String::InternalAllocateStr(System.Int32)", mscorlib::System::String::InternalAllocateStr)
REG_ICALL("System.String::InternalIntern(System.String)", mscorlib::System::String::InternalIntern)
REG_ICALL("System.String::InternalIsInterned(System.String)", mscorlib::System::String::InternalIsInterned)
REG_ICALL("System.String::InternalSplit(System.Char[],System.Int32,System.Int32)", mscorlib::System::String::InternalSplit)

// System.Text.Encoding
REG_ICALL("System.Text.Encoding::InternalCodePage(System.Int32&)", mscorlib::System::Text::Encoding::InternalCodePage)

// System.Threading.Interlocked
REG_ICALL("System.Threading.Interlocked::Add(System.Int32&,System.Int32)", mscorlib::System::Threading::Interlocked::Add)
REG_ICALL("System.Threading.Interlocked::Add(System.Int64&,System.Int64)", mscorlib::System::Threading::Interlocked::Add64)
REG_ICALL("System.Threading.Interlocked::CompareExchange(System.Double&,System.Double,System.Double)", mscorlib::System::Threading::Interlocked::CompareExchangeDouble)
REG_ICALL("System.Threading.Interlocked::CompareExchange(System.Int32&,System.Int32,System.Int32)", mscorlib::System::Threading::Interlocked::CompareExchange)
REG_ICALL("System.Threading.Interlocked::CompareExchange(System.Int64&,System.Int64,System.Int64)", mscorlib::System::Threading::Interlocked::CompareExchange64)
REG_ICALL("System.Threading.Interlocked::CompareExchange(System.IntPtr&,System.IntPtr,System.IntPtr)", mscorlib::System::Threading::Interlocked::CompareExchangeIntPtr)
REG_ICALL("System.Threading.Interlocked::CompareExchange(System.Object&,System.Object,System.Object)", mscorlib::System::Threading::Interlocked::CompareExchange_T)
REG_ICALL("System.Threading.Interlocked::CompareExchange(System.Single&,System.Single,System.Single)", mscorlib::System::Threading::Interlocked::CompareExchangeSingle)
REG_ICALL("System.Threading.Interlocked::CompareExchange(T&,T,T)", mscorlib::System::Threading::Interlocked::CompareExchange_T)
REG_ICALL("System.Threading.Interlocked::Decrement(System.Int32&)", mscorlib::System::Threading::Interlocked::Decrement)
REG_ICALL("System.Threading.Interlocked::Decrement(System.Int64&)", mscorlib::System::Threading::Interlocked::Decrement64)
REG_ICALL("System.Threading.Interlocked::Exchange(T&,T,T)", mscorlib::System::Threading::Interlocked::ExchangePointer)
REG_ICALL("System.Threading.Interlocked::Exchange(System.Double&,System.Double)", mscorlib::System::Threading::Interlocked::ExchangeDouble)
REG_ICALL("System.Threading.Interlocked::Exchange(System.Int32&,System.Int32)", mscorlib::System::Threading::Interlocked::Exchange)
REG_ICALL("System.Threading.Interlocked::Exchange(System.Int64&,System.Int64)", mscorlib::System::Threading::Interlocked::Exchange64)
REG_ICALL("System.Threading.Interlocked::Exchange(System.IntPtr&,System.IntPtr)", mscorlib::System::Threading::Interlocked::ExchangeIntPtr)
REG_ICALL("System.Threading.Interlocked::Exchange(System.Object&,System.Object)", mscorlib::System::Threading::Interlocked::ExchangePointer)
REG_ICALL("System.Threading.Interlocked::Exchange(System.Single&,System.Single)", mscorlib::System::Threading::Interlocked::ExchangeSingle)
REG_ICALL("System.Threading.Interlocked::Increment(System.Int32&)", mscorlib::System::Threading::Interlocked::Increment)
REG_ICALL("System.Threading.Interlocked::Increment(System.Int64&)", mscorlib::System::Threading::Interlocked::Increment64)
REG_ICALL("System.Threading.Interlocked::Read(System.Int64&)", mscorlib::System::Threading::Interlocked::Read)

// System.Threading.Monitor
REG_ICALL("System.Threading.Monitor::Enter(System.Object)", mscorlib::System::Threading::Monitor::Enter)
REG_ICALL("System.Threading.Monitor::Exit(System.Object)", mscorlib::System::Threading::Monitor::Exit)
REG_ICALL("System.Threading.Monitor::Monitor_pulse(System.Object)", mscorlib::System::Threading::Monitor::Monitor_pulse)
REG_ICALL("System.Threading.Monitor::Monitor_pulse_all(System.Object)", mscorlib::System::Threading::Monitor::Monitor_pulse_all)
REG_ICALL("System.Threading.Monitor::Monitor_test_synchronised(System.Object)", mscorlib::System::Threading::Monitor::Monitor_test_synchronised)
REG_ICALL("System.Threading.Monitor::Monitor_try_enter(System.Object,System.Int32)", mscorlib::System::Threading::Monitor::Monitor_try_enter)
REG_ICALL("System.Threading.Monitor::Monitor_wait(System.Object,System.Int32)", mscorlib::System::Threading::Monitor::Monitor_wait)

// System.Threading.Mutex
REG_ICALL("System.Threading.Mutex::CreateMutex_internal(System.Boolean,System.String,System.Boolean&)", mscorlib::System::Threading::Mutex::CreateMutex_internal)
REG_ICALL("System.Threading.Mutex::OpenMutex_internal(System.String,System.Security.AccessControl.MutexRights,System.IO.MonoIOError&)", mscorlib::System::Threading::Mutex::OpenMutex_internal)
REG_ICALL("System.Threading.Mutex::ReleaseMutex_internal(System.IntPtr)", mscorlib::System::Threading::Mutex::ReleaseMutex_internal)

// System.Threading.NativeEventCalls
REG_ICALL("System.Threading.NativeEventCalls::CloseEvent_internal(System.IntPtr)", mscorlib::System::Threading::NativeEventCalls::CloseEvent_internal)
REG_ICALL("System.Threading.NativeEventCalls::CreateEvent_internal(System.Boolean,System.Boolean,System.String,System.Boolean&)", mscorlib::System::Threading::NativeEventCalls::CreateEvent_internal)
REG_ICALL("System.Threading.NativeEventCalls::OpenEvent_internal(System.String,System.Security.AccessControl.EventWaitHandleRights,System.IO.MonoIOError&)", mscorlib::System::Threading::NativeEventCalls::OpenEvent_internal)
REG_ICALL("System.Threading.NativeEventCalls::ResetEvent_internal(System.IntPtr)", mscorlib::System::Threading::NativeEventCalls::ResetEvent_internal)
REG_ICALL("System.Threading.NativeEventCalls::SetEvent_internal(System.IntPtr)", mscorlib::System::Threading::NativeEventCalls::SetEvent_internal)

// System.Threading.Semaphore
REG_ICALL("System.Threading.Semaphore::CreateSemaphore_internal(System.Int32,System.Int32,System.String,System.Boolean&)", System::System::Threading::Semaphore::CreateSemaphore_internal)
REG_ICALL("System.Threading.Semaphore::OpenSemaphore_internal(System.String,System.Security.AccessControl.SemaphoreRights,System.IO.MonoIOError&)", System::System::Threading::Semaphore::OpenSemaphore_internal)
REG_ICALL("System.Threading.Semaphore::ReleaseSemaphore_internal(System.IntPtr,System.Int32,System.Boolean&)", System::System::Threading::Semaphore::ReleaseSemaphore_internal)

// System.Threading.Thread
REG_ICALL("System.Threading.Thread::Abort_internal(System.Object)", mscorlib::System::Threading::Thread::Abort_internal)
REG_ICALL("System.Threading.Thread::ClrState(System.Threading.ThreadState)", mscorlib::System::Threading::Thread::ClrState)
REG_ICALL("System.Threading.Thread::CurrentThread_internal()", mscorlib::System::Threading::Thread::CurrentThread_internal)
REG_ICALL("System.Threading.Thread::FreeLocalSlotValues(System.Int32,System.Boolean)", mscorlib::System::Threading::Thread::FreeLocalSlotValues)
REG_ICALL("System.Threading.Thread::GetAbortExceptionState()", mscorlib::System::Threading::Thread::GetAbortExceptionState)
REG_ICALL("System.Threading.Thread::GetCachedCurrentCulture()", mscorlib::System::Threading::Thread::GetCachedCurrentCulture)
REG_ICALL("System.Threading.Thread::GetCachedCurrentUICulture()", mscorlib::System::Threading::Thread::GetCachedCurrentUICulture)
REG_ICALL("System.Threading.Thread::GetDomainID()", mscorlib::System::Threading::Thread::GetDomainID)
REG_ICALL("System.Threading.Thread::GetName_internal()", mscorlib::System::Threading::Thread::GetName_internal)
REG_ICALL("System.Threading.Thread::GetNewManagedId_internal()", mscorlib::System::Threading::Thread::GetNewManagedId_internal)
REG_ICALL("System.Threading.Thread::GetSerializedCurrentCulture()", mscorlib::System::Threading::Thread::GetSerializedCurrentCulture)
REG_ICALL("System.Threading.Thread::GetSerializedCurrentUICulture()", mscorlib::System::Threading::Thread::GetSerializedCurrentUICulture)
REG_ICALL("System.Threading.Thread::GetState()", mscorlib::System::Threading::Thread::GetState)
REG_ICALL("System.Threading.Thread::Interrupt_internal()", mscorlib::System::Threading::Thread::Interrupt_internal)
REG_ICALL("System.Threading.Thread::Join_internal(System.Int32,System.IntPtr)", mscorlib::System::Threading::Thread::Join_internal)
REG_ICALL("System.Threading.Thread::MemoryBarrier()", mscorlib::System::Threading::Thread::MemoryBarrier_)
REG_ICALL("System.Threading.Thread::ResetAbort_internal()", mscorlib::System::Threading::Thread::ResetAbort_internal)
REG_ICALL("System.Threading.Thread::Resume_internal()", mscorlib::System::Threading::Thread::Resume_internal)
REG_ICALL("System.Threading.Thread::SetCachedCurrentCulture(System.Globalization.CultureInfo)", mscorlib::System::Threading::Thread::SetCachedCurrentCulture)
REG_ICALL("System.Threading.Thread::SetCachedCurrentUICulture(System.Globalization.CultureInfo)", mscorlib::System::Threading::Thread::SetCachedCurrentUICulture)
REG_ICALL("System.Threading.Thread::SetName_internal(System.String)", mscorlib::System::Threading::Thread::SetName_internal)
REG_ICALL("System.Threading.Thread::SetSerializedCurrentCulture(System.Byte[])", mscorlib::System::Threading::Thread::SetSerializedCurrentCulture)
REG_ICALL("System.Threading.Thread::SetSerializedCurrentUICulture(System.Byte[])", mscorlib::System::Threading::Thread::SetSerializedCurrentUICulture)
REG_ICALL("System.Threading.Thread::SetState(System.Threading.ThreadState)", mscorlib::System::Threading::Thread::SetState)
REG_ICALL("System.Threading.Thread::Sleep_internal(System.Int32)", mscorlib::System::Threading::Thread::Sleep_internal)
REG_ICALL("System.Threading.Thread::SpinWait_nop()", mscorlib::System::Threading::Thread::SpinWait_nop)
REG_ICALL("System.Threading.Thread::Suspend_internal()", mscorlib::System::Threading::Thread::Suspend_internal)
REG_ICALL("System.Threading.Thread::Thread_free_internal(System.IntPtr)", mscorlib::System::Threading::Thread::Thread_free_internal)
REG_ICALL("System.Threading.Thread::Thread_init()", mscorlib::System::Threading::Thread::Thread_init)
REG_ICALL("System.Threading.Thread::Thread_internal(System.MulticastDelegate)", mscorlib::System::Threading::Thread::Thread_internal)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Byte&)", mscorlib::System::Threading::Thread::VolatileReadInt8)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Double&)", mscorlib::System::Threading::Thread::VolatileReadDouble)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Int16&)", mscorlib::System::Threading::Thread::VolatileReadInt16)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Int32&)", mscorlib::System::Threading::Thread::VolatileReadInt32)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Int64&)", mscorlib::System::Threading::Thread::VolatileReadInt64)
REG_ICALL("System.Threading.Thread::VolatileRead(System.IntPtr&)", mscorlib::System::Threading::Thread::VolatileReadIntPtr)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Object&)", mscorlib::System::Threading::Thread::VolatileReadPtr)
REG_ICALL("System.Threading.Thread::VolatileRead(System.SByte&)", mscorlib::System::Threading::Thread::VolatileReadInt8)
REG_ICALL("System.Threading.Thread::VolatileRead(System.Single&)", mscorlib::System::Threading::Thread::VolatileReadFloat)
REG_ICALL("System.Threading.Thread::VolatileRead(System.UInt16&)", mscorlib::System::Threading::Thread::VolatileReadInt16)
REG_ICALL("System.Threading.Thread::VolatileRead(System.UInt32&)", mscorlib::System::Threading::Thread::VolatileReadInt32)
REG_ICALL("System.Threading.Thread::VolatileRead(System.UInt64&)", mscorlib::System::Threading::Thread::VolatileReadInt64)
REG_ICALL("System.Threading.Thread::VolatileRead(System.UIntPtr&)", mscorlib::System::Threading::Thread::VolatileReadIntPtr)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Byte&,System.Byte)", mscorlib::System::Threading::Thread::VolatileWriteInt8)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Double&,System.Double)", mscorlib::System::Threading::Thread::VolatileWriteDouble)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Int16&,System.Int16)", mscorlib::System::Threading::Thread::VolatileWriteInt16)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Int32&,System.Int32)", mscorlib::System::Threading::Thread::VolatileWriteInt32)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Int64&,System.Int64)", mscorlib::System::Threading::Thread::VolatileWriteInt64)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.IntPtr&,System.IntPtr)", mscorlib::System::Threading::Thread::VolatileWriteIntPtr)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Object&,System.Object)", mscorlib::System::Threading::Thread::VolatileWritePtr)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.SByte&,System.SByte)", mscorlib::System::Threading::Thread::VolatileWriteInt8)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.Single&,System.Single)", mscorlib::System::Threading::Thread::VolatileWriteFloat)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.UInt16&,System.UInt16)", mscorlib::System::Threading::Thread::VolatileWriteInt16)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.UInt32&,System.UInt32)", mscorlib::System::Threading::Thread::VolatileWriteInt32)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.UInt64&,System.UInt64)", mscorlib::System::Threading::Thread::VolatileWriteInt64)
REG_ICALL("System.Threading.Thread::VolatileWrite(System.UIntPtr&,System.UIntPtr)", mscorlib::System::Threading::Thread::VolatileWriteIntPtr)

// System.Threading.ThreadPool
REG_ICALL("System.Threading.ThreadPool::GetAvailableThreads(System.Int32&,System.Int32&)", mscorlib::System::Threading::ThreadPool::GetAvailableThreads)
REG_ICALL("System.Threading.ThreadPool::GetMaxThreads(System.Int32&,System.Int32&)", mscorlib::System::Threading::ThreadPool::GetMaxThreads)
REG_ICALL("System.Threading.ThreadPool::GetMinThreads(System.Int32&,System.Int32&)", mscorlib::System::Threading::ThreadPool::GetMinThreads)
REG_ICALL("System.Threading.ThreadPool::SetMaxThreads(System.Int32,System.Int32)", mscorlib::System::Threading::ThreadPool::SetMaxThreads)
REG_ICALL("System.Threading.ThreadPool::SetMinThreads(System.Int32,System.Int32)", mscorlib::System::Threading::ThreadPool::SetMinThreads)

// System.Threading.WaitHandle
REG_ICALL("System.Threading.WaitHandle::SignalAndWait_Internal(System.IntPtr,System.IntPtr,System.Int32,System.Boolean)", mscorlib::System::Threading::WaitHandle::SignalAndWait_Internal)
REG_ICALL("System.Threading.WaitHandle::WaitAll_internal(System.Threading.WaitHandle[],System.Int32,System.Boolean)", mscorlib::System::Threading::WaitHandle::WaitAll_internal)
REG_ICALL("System.Threading.WaitHandle::WaitAny_internal(System.Threading.WaitHandle[],System.Int32,System.Boolean)", mscorlib::System::Threading::WaitHandle::WaitAny_internal)
REG_ICALL("System.Threading.WaitHandle::WaitOne_internal(System.IntPtr,System.Int32,System.Boolean)", mscorlib::System::Threading::WaitHandle::WaitOne_internal)

// System.Type
REG_ICALL("System.Type::EqualsInternal(System.Type)", mscorlib::System::Type::EqualsInternal)
REG_ICALL("System.Type::get_IsGenericType()", mscorlib::System::Type::get_IsGenericType)
REG_ICALL("System.Type::get_IsGenericTypeDefinition()", mscorlib::System::Type::get_IsGenericTypeDefinition)
REG_ICALL("System.Type::GetGenericParameterAttributes()", mscorlib::System::Type::GetGenericParameterAttributes)
REG_ICALL("System.Type::GetGenericParameterConstraints_impl()", mscorlib::System::Type::GetGenericParameterConstraints_impl)
REG_ICALL("System.Type::GetGenericParameterPosition()", mscorlib::System::Type::GetGenericParameterPosition)
REG_ICALL("System.Type::GetGenericTypeDefinition_impl()", mscorlib::System::Type::GetGenericTypeDefinition_impl)
REG_ICALL("System.Type::GetInterfaceMapData(System.Type,System.Type,System.Reflection.MethodInfo[]&,System.Reflection.MethodInfo[]&)", mscorlib::System::Type::GetInterfaceMapData)
REG_ICALL("System.Type::GetPacking(System.Int32&,System.Int32&)", mscorlib::System::Type::GetPacking)
REG_ICALL("System.Type::GetTypeCodeInternal(System.Type)", mscorlib::System::Type::GetTypeCodeInternal)
REG_ICALL("System.Type::internal_from_handle(System.IntPtr)", mscorlib::System::Type::internal_from_handle)
REG_ICALL("System.Type::internal_from_name(System.String,System.Boolean,System.Boolean)", mscorlib::System::Type::internal_from_name)
REG_ICALL("System.Type::IsArrayImpl(System.Type)", mscorlib::System::Type::IsArrayImpl)
REG_ICALL("System.Type::IsInstanceOfType(System.Object)", mscorlib::System::Type::IsInstanceOfType)
REG_ICALL("System.Type::make_array_type(System.Int32)", mscorlib::System::Type::make_array_type)
REG_ICALL("System.Type::make_byref_type()", mscorlib::System::Type::make_byref_type)
REG_ICALL("System.Type::MakeGenericType(System.Type,System.Type[])", mscorlib::System::Type::MakeGenericType)
REG_ICALL("System.Type::MakePointerType()", mscorlib::System::Type::MakePointerType)
REG_ICALL("System.Type::type_is_assignable_from(System.Type,System.Type)", mscorlib::System::Type::type_is_assignable_from)
REG_ICALL("System.Type::type_is_subtype_of(System.Type,System.Type,System.Boolean)", mscorlib::System::Type::type_is_subtype_of)

// System.TypedReference
REG_ICALL("System.TypedReference::ToObject(System.TypedReference)", mscorlib::System::TypedReference::ToObject)

// System.ValueType
REG_ICALL("System.ValueType::InternalEquals(System.Object,System.Object,System.Object[]&)", mscorlib::System::ValueType::InternalEquals)
REG_ICALL("System.ValueType::InternalGetHashCode(System.Object,System.Object[]&)", mscorlib::System::ValueType::InternalGetHashCode)
